services:
  - type: web
    name: tiktok-affiliator
    env: node
    buildCommand: |
      npm ci
      npx puppeteer browsers install chrome
      npm run build-only
    startCommand: npm run start
